uw-ssec/phylo2vec

- pixi.lock
- pixi.toml
- py-phylo2vec/README.md
This pull request includes changes to the `pixi.toml` file to reorganize and modularize the build and dependency management for the `py-phylo2vec` and `r-phylo2vec` environments. Additionally, the `py-phylo2vec/README.md` file has been updated to reflect these changes.
Changes to `pixi.toml`:
* Reorganized the dependency and task management for `py-phylo2vec` and `r-phylo2vec` into separate feature sections. [[1]](diffhunk://#diff-b092682f0ad15a352f9fa2b0a67c992454b586275ee76b74a5839ab9afdf9894L31-L50) [[2]](diffhunk://#diff-b092682f0ad15a352f9fa2b0a67c992454b586275ee76b74a5839ab9afdf9894R51-R73)
* Added environment definitions for `py-phylo2vec` and `r-phylo2vec`.
Updates to `py-phylo2vec/README.md`:
* Updated the installation and usage instructions to use the new environment-specific …
> chore: Split python dependencies and add initial r deps

- Cargo.lock
- phylo2vec/Cargo.toml
- phylo2vec/benches/bench_main.rs
- phylo2vec/benches/benchmarks/get_pairs.rs
- phylo2vec/benches/benchmarks/mod.rs
- pixi.toml
This pull request introduces benchmarking for the `phylo2vec` project using the Criterion library. The changes include adding dependencies, creating a benchmark entry point, and defining benchmark tests for specific functions.
* [`phylo2vec/Cargo.toml`](diffhunk://#diff-1e1607779e56d3d4547e09d9f0d008f8f0a8d373e91cbe34b8457915428a53c8R14-R22): Added `criterion` as a development dependency and configured the benchmark harness.
* [`phylo2vec/benches/bench_main.rs`](diffhunk://#diff-25361157b0e801bfc9ff46c3cc00dbe1e33db47655487f46bdbc4b020fc18661R1-R5): Created the main entry point for Criterion benchmarks.
* [`phylo2vec/benches/benchmarks/get_pairs.rs`](diffhunk://#diff-047212cf9a39d84cab757e940cbb7ca9db8fad8f3a3351e52d97386157bedcfaR1-R60): Defined benchmarks for `get_pairs` and …
> chore: Add benchmarking for rust get_pairs

- .github/workflows/ci-rust.yaml
- phylo2vec/src/avl.rs
- phylo2vec/src/lib.rs
- phylo2vec/src/main.rs
- phylo2vec/src/to_newick.rs
- phylo2vec/src/utils.rs
- py-phylo2vec/src/lib.rs
This pull request introduces a new GitHub Actions workflow for continuous integration (CI) of Rust projects. The workflow is designed to run on different Rust toolchains and includes steps for checking code formatting, compiling the code, and running tests.
Key changes include:
* [`.github/workflows/ci-rust.yaml`](diffhunk://#diff-e0a44f932f567f558ec52679921ccef351a14659e9c5023318192395edb30c63R1-R32): Added a new CI workflow configuration for Rust projects that triggers on pushes to `main` and `dev` branches and on pull requests. This workflow sets up the Rust environment, runs a linter, compiles the code, and executes tests.
> ci: Add CI for Rust

- phylo2vec/src/utils.rs
This pull request includes changes to the `phylo2vec/src/utils.rs` file to enhance the validation and testing of the Phylo2Vec vector elements. The most important changes include refactoring the `check_v` function, adding a new helper function `_check_max`, introducing a new function `is_unordered`, and updating the tests accordingly.
Validation improvements:
* Refactored the `check_v` function to use a new helper function `_check_max` for validating the maximum value of each element in the vector. This change improves code readability and maintainability.
* Added a new function `_check_max` that validates the maximum value of a Phylo2Vec vector element, ensuring that values do not exceed `2 * idx`. This function includes detailed documentation and a panic message for out-of-bounds …
> feat: Add is_unordered function and modify max validator

- .github/workflows/cd-python.yaml
This pull request includes a small change to the `.github/workflows/cd-python.yaml` file. The change removes the `pull_request` trigger from the workflow configuration.
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265L10): Removed the `pull_request` trigger from the `on:` section of the workflow configuration.
> ci: Remove CD running on PRs

- phylo2vec/src/tree_vec/mod.rs
- phylo2vec/src/tree_vec/ops/mod.rs
- phylo2vec/src/tree_vec/ops/vector.rs
- py-phylo2vec/src/lib.rs
This pull request introduces several new features and improvements to the `TreeVec` struct in the `phylo2vec` library. The changes include new methods for manipulating the tree structure, additional documentation, and new tests to ensure functionality.
* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R46-R168): Added new methods `add_leaf`, `remove_leaf`, and `from_sample` to the `TreeVec` struct, allowing for dynamic manipulation of the tree structure.
* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R46-R168): Implemented the `to_newick` method to convert the tree to Newick format and updated the `get_ancestry` method to return an `Ancestry` type.
* …
> feat: Add 'add_leaf' and 'remove_leaf' methods

- .github/workflows/cd-python.yaml
This pull request includes changes to the continuous deployment workflow configuration for Python projects. The most important change involves updating the macOS platform version and target architecture used in the CI/CD pipeline.
Changes to CI/CD pipeline configuration:
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265L117-L118): Updated the `jobs:` section to remove macOS 12 with x86_64 target and add macOS 14 with aarch64 target.
> ci: Remove deprecated macos-12 build

- phylo2vec/README.md
This pull request includes a new `README.md` file for the `phylo2vec` project written in Rust. The main changes include the addition of a project description and details about the directory structure and important files.
Documentation improvements:
* [`phylo2vec/README.md`](diffhunk://#diff-221eb145ead49aa0366836a39ede41088d6098ddbb9cb7db4dccad8cd5a50ecfR1-R18): Added a comprehensive description of the `phylo2vec` project, including information about the Rust codebase, important subdirectories (`benches/`, `src/`), and the `Cargo.toml` configuration file.
> docs: Add a small readme for rust directory

- phylo2vec/README.md
This pull request includes a minor change to the `phylo2vec/README.md` file to improve readability by breaking long lines into shorter ones.
Documentation improvements:
* [`phylo2vec/README.md`](diffhunk://#diff-221eb145ead49aa0366836a39ede41088d6098ddbb9cb7db4dccad8cd5a50ecfL3-R7): Reformatted long lines to improve readability. [[1]](diffhunk://#diff-221eb145ead49aa0366836a39ede41088d6098ddbb9cb7db4dccad8cd5a50ecfL3-R7) [[2]](diffhunk://#diff-221eb145ead49aa0366836a39ede41088d6098ddbb9cb7db4dccad8cd5a50ecfL17-R19)
> style: Perform style fix on phylo2vec readme

- phylo2vec/benches/benchmarks/get_ancestry_dtype.rs
- phylo2vec/src/tree_vec/mod.rs
- phylo2vec/src/tree_vec/ops/avl.rs
- phylo2vec/src/tree_vec/ops/mod.rs
- phylo2vec/src/tree_vec/ops/newick.rs
- phylo2vec/src/tree_vec/ops/vector.rs
- phylo2vec/src/tree_vec/types.rs
- py-phylo2vec/src/lib.rs
This pull request involves several changes to the `phylo2vec` library, focusing on code organization and refactoring. The primary changes include moving type definitions to a new `types` module, updating import paths, and refactoring functions to use the new module. Additionally, a new `newick` module has been introduced to handle Newick string construction.
* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R3-L6): Introduced a new `types` module and updated type references to use this module. [[1]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9R3-L6) [[2]](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9L71-R72) …
> refactor: Perform codebase refactor to separate appropriate functions

- phylo2vec/src/tree_vec/mod.rs
- phylo2vec/src/tree_vec/ops/mod.rs
- phylo2vec/src/tree_vec/ops/newick.rs
- phylo2vec/src/tree_vec/ops/vector.rs
This pull request introduces several changes to the `phylo2vec` module, focusing on improving the handling of Newick format trees and the corresponding vector operations. The most important changes include the addition of a function to convert Newick format strings to vectors, updates to vector construction functions, and the addition of tests for these new functionalities.
* [`phylo2vec/src/tree_vec/ops/mod.rs`](diffhunk://#diff-981749b2e0b574fedc34b8672f862e4d574c2b97eb58220bc6cd3af30cb06a3aR19-R78): Added `from_newick` function to convert Newick format strings to vectors, with an option to handle trees with or without parent nodes.
* [`phylo2vec/src/tree_vec/mod.rs`](diffhunk://#diff-93651a78de451eb71d57f7b5f50421603e29b7607e886401e3e60bc90d8c8de9L108-R108): Updated calls to …
> feat: Add from_newick function to parse newick string

- pixi.toml
This pull request includes updates to the `pixi.toml` file, specifically focusing on the installation and testing commands for the Python tasks.
Key changes:
* Updated the `cmd` for the `install-python` task to include the `--release` flag, which ensures that the Python package is built in release mode.
* Removed the `test-rust` task, which previously ran Rust library tests in the `py-phylo2vec` directory.
> build: Fix build to be release for python dev rust compilation

- py-phylo2vec/phylo2vec/base/to_newick.py
- py-phylo2vec/phylo2vec/metrics/pairwise.py
- py-phylo2vec/phylo2vec/utils/random.py
- py-phylo2vec/phylo2vec/utils/validation.py
- py-phylo2vec/phylo2vec/utils/vector.py
- py-phylo2vec/src/lib.rs
This pull request includes significant refactoring of the `phylo2vec` package, primarily focusing on removing `numba` dependencies and replacing internal function implementations with calls to a Rust core module. The most important changes include modifications to the `to_newick` conversion process, updates in utility functions, and adjustments in the Rust bindings.
Refactoring and dependency removal:
* Removed `numba` dependency and associated JIT-compiled functions from `py-phylo2vec/phylo2vec/base/to_newick.py`, replacing them with calls to the Rust core module (`_phylo2vec_core`). [[1]](diffhunk://#diff-90bfd32ed07993e02e8ea423e79fb1b4a62e64cf49a7e7f4c89384356f322fecL4-R8) [[2]](diffhunk://#diff-90bfd32ed07993e02e8ea423e79fb1b4a62e64cf49a7e7f4c89384356f322fecL80-R46) …
> feat: Integrate binding to python rust core and clean up

- .github/dependabot.yml
- .github/release.yml
This pull request includes updates to configuration files for GitHub Actions and release management. The most important changes include the addition of a Dependabot configuration file and the exclusion of certain authors from the changelog.
Configuration updates:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R11): Added a new configuration file to maintain dependencies for GitHub Actions with a weekly update schedule.
* [`.github/release.yml`](diffhunk://#diff-409fea45635f464aa0592700a92cf483be2f5b21b60f8f1b383756067ee79213R1-R7): Updated the release configuration to exclude specific authors from the changelog.
> ci: Add dependabot and release config

- phylo2vec/src/tree_vec/ops/mod.rs
This pull request includes several changes to the `phylo2vec/src/tree_vec/ops/mod.rs` file, primarily focusing on renaming a function and updating corresponding test cases. The most important changes include renaming the `from_newick` function to `to_vector` and simplifying its implementation by removing the `has_parents` parameter.
Function renaming and simplification:
* Renamed the `from_newick` function to `to_vector` and removed the `has_parents` parameter. The function now determines if the Newick string has parents internally and processes it accordingly.
Test case updates:
* Updated the `test_from_newick` test case to `test_to_vector` to match the new function name and removed the `has_parents` parameter.
* Updated the `test_from_newick_no_parents` test case to …
> refactor: Change 'from_newick' to 'to_vector'

- benchmarks/bench_sample_kl.py
- py-phylo2vec/phylo2vec/base/__init__.py
- py-phylo2vec/phylo2vec/base/to_vector.py
- py-phylo2vec/phylo2vec/utils/vector.py
- py-phylo2vec/src/lib.rs
- py-phylo2vec/tests/test_v2newick2v.py
This pull request includes significant refactoring and simplification of the `phylo2vec` codebase by removing the `to_vector_no_parents` function and consolidating its functionality into the `to_vector` function. Additionally, there are some type changes and updates to related tests and utility functions. The most important changes include the removal of `to_vector_no_parents`, updates to the `to_vector` function to handle both cases, and corresponding changes in imports and tests.
Refactoring and simplification:
* [`py-phylo2vec/phylo2vec/base/to_vector.py`](diffhunk://#diff-6288d4e90180e21cb9867043b4a6809e91adb0b4814ebcbf76ebcad75fef80c7L154-R156): Removed the `to_vector_no_parents` function and updated the `to_vector` function to handle Newick strings with or without parent labels.
* …
> feat: Integrate 'to_vector', removing '*_no_parents'

- .github/workflows/cd-python.yaml
This pull request includes changes to the `.github/workflows/cd-python.yaml` file to update the continuous deployment workflow for the Python project. The most important changes include modifying the trigger conditions for the workflow and updating the release job configuration.
Changes to workflow triggers:
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265L8-R11): Removed the `tags` trigger and added a `release` trigger with the `published` type.
Updates to release job configuration:
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265L154-R159): Added an `environment` parameter set to `pypi` and updated the `if` condition to check for a `release` …
> ci: Update CD to use trusted publishing

- .github/workflows/ci-python.yml
- pixi.lock
- pixi.toml
- py-phylo2vec/pyproject.toml
This pull request includes several updates to the CI configuration and environment setup for the `phylo2vec` project. The main changes involve adding support for multiple Python environments and restructuring the environment definitions in the `pixi.toml` file.
* [`.github/workflows/ci-python.yml`](diffhunk://#diff-a7ec86144013d78c9f1d734aa65a898e66b609638aa7b872491ee3858ebebbebL14-R29): Updated the CI workflow to support multiple Python environments (`py310`, `py311`, `py312`) and removed the hardcoded `PIXI_PYTHON_ENV` variable.
* `pixi.toml`: 
* Added new environment definitions for `py310`, `py311`, and `py312`.
* Restructured the `py-phylo2vec` and `r-phylo2vec` environments to include features and solve groups.
* Updated feature dependencies to specify Python versions (`3.10.*`, …
> ci: Add multi python version configuration for testing

- .github/workflows/cd-python.yaml
This pull request includes a change to the continuous deployment workflow configuration for Python projects. The most important change is the addition of a new platform to the matrix strategy in the `.github/workflows/cd-python.yaml` file.
Changes to continuous deployment workflow:
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265R118-R119): Added `macos-13` with `x86_64` target to the matrix strategy under `jobs:`.
> ci: Add mising macos x86_64 build

- phylo2vec/src/utils.rs
This pull request includes a change to the `is_unordered` function in the `phylo2vec/src/utils.rs` file to improve its efficiency. The most important change is the modification of the function to return immediately when an unordered element is found, instead of using a flag to track the state.
Efficiency improvement:
* [`phylo2vec/src/utils.rs`](diffhunk://#diff-155285a0bd35d816f33d8bee80a64827236d8624f2cf4b81826af93d28fe6842L96-R103): Modified the `is_unordered` function to return `true` immediately when an unordered element is found, and `false` otherwise. This change eliminates the need for the `unordered` variable and reduces the number of iterations in some cases.
Closes #37
> refactor: Update 'is_unordered' to return early for first instance

- phylo2vec/src/tree_vec/ops/avl.rs
- phylo2vec/src/tree_vec/types.rs
nits:
- In `types.rs`, added `/` for consistency so the comment would appear in doc comments
- In `avl.rs`, renamed `get_balance` to `get_balance_factor` and added comments for clarity; renamed `update` to `update_height_and_size` for clarity
> nits in avl.rs

- .github/workflows/ci-python.yml
- pixi.lock
- pixi.toml
- py-phylo2vec/benchmarks/test_bench.py
Create a suite of benchmarks for the Rust to python bindings. Uses [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark). There is also potential to create a GH action using this suite with [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark).
Closes #9
> test: Add benchmarking suite for rust bindings

- .github/workflows/cd-python.yaml
- pixi.toml
- resources/update_python_version.py
This pull request includes significant updates to the continuous deployment workflow and introduces a new script for version management. The most important changes include adding a new job to update the version using a timestamp, modifying existing jobs to depend on this new job, and adding a new Python script for version management.
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265R20-R54): Added a new `update-version` job to determine and set the version based on the event type (release or timestamp). All existing jobs (`linux`, `musllinux`, `windows`, `macos`, `sdist`, and `publish`) now depend on this new job. Additionally, a new `test-release` job has been added to handle non-release events. …
> ci: Add python version update script and update CD config

- .github/workflows/cd-python.yaml
This pull request includes a change to the `.github/workflows/cd-python.yaml` file to improve the publishing process to TestPyPI by setting an environment variable and updating the command arguments.
Improvements to the publishing process:
* [`.github/workflows/cd-python.yaml`](diffhunk://#diff-3d3ec9b0267b381030bac62bc8c1fba27934e0747af2b539b83a62643cc93265R264-R268): Added the `MATURIN_REPOSITORY` environment variable and updated the `args` to simplify the upload command.
> fix: Add maturin repository env var for testpypi
